[tool.poetry]
name = "madr"
version = "0.1.0"
description = ""
authors = ["2005869 <2005869@aluno.univesp.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
